# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Tags for Blog based on Today's Date

on:
  push:
    paths-ignore:
    - 'README.md'

    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip freeze > scripts/generate_tags/requirements.txt
        pip install -r scripts/generate_tags/requirements.txt
    - name: Run generate tags script
      run: |
        python scripts/generate_tags/generate_tags.py -t
    - name: Create commits
      run: |
          echo "username: ${{github.actor}}"
          echo "email: ${{github.email}}"
        
          git config user.name {{github.actor}}
          git config user.email 'kenshin579@hotmail.com'
          git add README.md
          git commit -am "update tags"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update index.md files
        branch: tags-patches
        delete-branch: true
        title: '[AUTO] Update index.md file'
        body: |
          Update Tags
        labels: |
          automated pr
        assignees: kenshin579
        reviewers: kenshin579
